name: Deploy Static HTML App to Azure Web App - Unicon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D0F12200CBC54BD38A9C4B507F3A1EDA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6BC80C23D5174E839DF0892B0419D1DE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8DB2B87708CB42D696B047A92F812DC9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Unicon'
          slot-name: 'Production'
          package: ./public
