name: Deploy Static Site to Azure Web App - Unicon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Unicon'  # Replace with your Azure Web App name
          slot-name: 'Production'
          package: ./  # This points to the directory containing your index.html
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
