name: Deploy Static Site to Azure Web App - Unicon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload Static Site Files
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: ./ # Include all files (index.html, CSS, JS, etc.)

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Static Site Files
        uses: actions/download-artifact@v4
        with:
          name: static-site

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Unicon'
          package: ./ # Ensure this points to the correct folder
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
