# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy static HTML app to Azure Web App - Unicon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_51A38FFA393D41E0A88A0C5B061E0B58 }}
         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BC379EAA5DF044B78F1B6D2476E10835 }}
         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EEAAEB7841E492F95CB96DBE0C7F0B7 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Unicon'
          slot-name: 'Production' # Ensure the slot name exists in your Azure App Service
          package: './' # Deploy the root directory containing the HTML app files

      
     
